### ISSUE TITLE
record system stats for instance SIOT is running on

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#108]
CPU usage, disk usage, network stats, CPU Temp, etc.

@kraj Did you already start work on something like this?

**Comment by cbrake** [comment]
Implementation suggestions:

1. start a new goroutine that looks at system stats and sends them via NATS. Could start goroutine [here](https://github.com/simpleiot/simpleiot/blob/master/cmd/master/main.go#L634). 
2. perhaps implement system stats goroutine in this [dir](https://github.com/simpleiot/simpleiot/tree/master/system)
3. see example of how to send new points [here](https://github.com/simpleiot/simpleiot/blob/master/cmd/siot/main.go#L286), and [here](https://github.com/simpleiot/simpleiot/blob/master/node/modbus.go#L227)

**Comment by cbrake** [comment]
there is a lot of existing code that captures system stats: https://pkg.go.dev/search?q=system+stats

https://pkg.go.dev/github.com/prometheus/node_exporter@v1.0.1

If we have a choice, something with less dependencies, but that is not super important right now -- we can always optimize later.

**Comment by kraj** [comment]
thanks @cbrake my method was using system utilities like uptime to collect the info which I do not like. I think writing a proper go routine to do this is much better way.
