### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by kdsch** [simpleiot/simpleiot#22]
@cbrake My assumptions:

1. Use SSL to prevent password exposure upon initial authentication
2. Backend will serve a JWT to the frontend, which will have to send it along with every request

**Comment by kdsch** [comment]
Adding SSL support trivial; substituting `http.ListenAndServeTLS` for `http.ListenAndServe`.

This would also impact devices, requiring them to specify `https://`, since both devices and users are served by the same backend instance. I think this is the only impact on devices.

@cbrake Are you able to get some CA-signed certificates (from Let's Encrypt, for instance) for us to use? If not, I'll try using self-signed certs for local testing.

I've always found dealing with certs to be a hassle.

**Comment by cbrake** [comment]
I would assume SSL will be handled outside of siot -- it is trivial to set up a caddy2 server and it handles the cert stuff with letsencrypt -- plus you typically need a web server anyway to handle multiple apps, etc. I also think that on services like appengine, https needs to be handled outside the app.

**Comment by cbrake** [comment]
certs is a hassle until you use caddy/caddy2 :-)

I've successfully set up a local HTTPS setup using caddy2 + mkcert -- that works pretty well. But for testing on this task, you probably don't need to worry about local certs.

**Comment by cbrake** [comment]
some ideas for the frontend side: https://blog.thesett.com/

There are several elm jwt libs: https://package.elm-lang.org/

And go packages: https://pkg.go.dev/search?q=jwt

(not saying we should use one, but should probably at least look at them)

**Comment by kdsch** [comment]
@cbrake Thanks for the clarification about SSL. I intend to work on this today.

Sorry about the dup ticket! Not sure how I missed it.

**Comment by cbrake** [comment]
NP, at some point we might add HTTPS support directly in SIOT (perhaps using https://github.com/mholt/certmagic), but for immediate use cases, we always have caddy on a server, because each server does multiple things anyway.

**Comment by kdsch** [comment]
@cbrake Does https://github.com/simpleiot/simpleiot/tree/feature-elm-spa-dev make any assumptions about the login API? I checked out the code but it looks like frontend2 is not being built by the envsetup commands.

I don't see a reason to deviate from the approach detailed in the section ["How do JSON Web Tokens work?"](https://jwt.io/introduction/), aside from not using a separate server for authorization.

**Comment by cbrake** [comment]
@kdsch no, I don't have any server communication implemented yet in the feature-elm-spa-dev branch. I would just add a REST api for auth that fits in with what is already there. We can also look at APIs others have done:

https://docs.particle.io/reference/device-cloud/api/#authentication
https://hologram.io/docs/reference/cloud/http/#/introduction/authentication
https://auth0.com/docs/api/authentication#introduction

I've not studied the above to see if they are relevant, but sometimes you can get good ideas.

**Comment by kdsch** [comment]
I've worked with JWT on the client side but not the server. I'm finding it complex, but I've never written stateless auth before. In any case, other people also have found JWT complex, poorly designed, and incorrectly used in practice:

https://lobste.rs/s/dkk1ny/things_use_instead_jwt

If the goal is to have stateless auth (which I presume is implied by REST), then I think we should still go with JWT. But I'd like to do more research to ensure that we use it correctly.

**Comment by cbrake** [comment]
yes, it does look complex -- just read through: https://auth0.com/blog/stateless-auth-for-stateful-minds/

Would using sessions be the "stateful" approach?

I was not implying stateful vs stateless with REST -- more just that we would send login/pass to a REST api that would return a token, that could be used for subsequent requests. It seems like stateless is nice if we can implement without too much pain.

**Comment by cbrake** [comment]
the realworld app implements auth: 

https://github.com/gothinkster/realworld/tree/master/api#authentication

Here is an example of one Go implementation doing the JWT stuff: 

https://github.com/chilledoj/realworld-starter-kit/blob/master/models/token.go

**Comment by kdsch** [comment]
Good examples, more complex than what I've explored so far. Thanks!

My takeaway about the risks of JWT is that validity comprises several conditions:

```
func (auth Auth) ValidToken(str string) bool {
  token, err := jwt.Parse(str, auth.keyFunc)
  return err == nil &&
    token.Method.Alg() == "HS256" &&
    token.Valid
}
```

**Comment by cbrake** [comment]
@kdsch the basic frontend code is finished for sign-in UI -- I merged the feature-elm-spa-dev branch to master, and the frontend2 contains the new UI code. I'll try to merge the other functionality from the old frontend branch, and integrate building of the assets into envsetup.sh.

**Comment by cbrake** [comment]
implemented in feature-auth branch.
