### ISSUE TITLE
use go:embed for embedded assets

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#252]

**Comment by nathan-415** [comment]
I would like to work on this, I am new to OSS could you please give me a few pointers to where and how I can address this issue? Thanks

**Comment by cbrake** [comment]
We currently use genesis for embedded assets in the SIOT binary: 

* https://github.com/simpleiot/simpleiot/blob/master/envsetup.sh#L5
* https://github.com/simpleiot/simpleiot/blob/master/envsetup.sh#L64

and then we use these assets here in the program:

* https://github.com/simpleiot/simpleiot/blob/master/api/server.go#L71
* https://github.com/simpleiot/simpleiot/blob/master/cmd/siot/main.go#L508

With go:embed, embedding assets is now built into Go, so we no longer need to rely on 3rd party packages like genesis. Some information on go:embed.

* https://pkg.go.dev/embed
* https://blog.carlmjohnson.net/post/2021/how-to-use-go-embed/
* https://changelog.com/gotime/171

As far as workflow, you'll want to fork this repo into your own github space, make and test the changes, and then open a PR request.

Let me know if you have any questions.

**Comment by nathan-415** [comment]
Thank You for the detailed write up! It helped me a lot!

**Comment by cbrake** [comment]
need to investigate if we can check in frontend assets and have go:embed use them during `go get`

cc: @bminer

**Comment by bminer** [comment]
See related #340

I confirmed that checking in frontend assets and using go:embed works during `go get`. Cool!

**Comment by cbrake** [comment]
implemented in #438
