### ISSUE TITLE
Ui is rest or push based

### ISSUE THREAD

**Issue by gedw99** [simpleiot/simpleiot#267]
Am playing around with gio UI, and docs sas its rest based, but i see a websocket handler that is not linked to by any code.

So seems its all rest API now ? I guess it is polling ?

I think that WASM nats can work using the golang nats client. Others have done it.

Just opening up the conversion to get feedback..

**Comment by gedw99** [comment]
old

**Comment by cbrake** [comment]
yes, polling -- very primitive right now, but functional for the immediate projects so I can focus on functionality.
