### ISSUE TITLE
change protobuf point.value encoding from float to double

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#291]
does a make a big difference on arm32 architectures? Is there any advantage to float64 for most applications, where we typically only care about a couple decimal places?

@kraj do you have any opinions on this?

**Comment by kraj** [comment]
here are results on beaglebone black

```
Enter array size (q to quit) [200]:  Memory required:  315K.


LINPACK benchmark, Double precision.
Machine precision:  15 digits.
Array size 200 X 200.
Average rolled and unrolled performance:

    Reps Time(s) DGEFA   DGESL  OVERHEAD    KFLOPS
----------------------------------------------------
      16   0.53  92.93%   2.90%   4.17%  43650.975
      32   1.05  92.91%   2.90%   4.19%  43621.772
      64   2.10  92.92%   2.90%   4.18%  43655.766
     128   4.21  92.91%   2.92%   4.18%  43601.366
     256   8.41  92.91%   2.91%   4.18%  43612.518
     512  16.82  92.91%   2.91%   4.18%  43616.980

^C
root@beaglebone:~# linpack_sp

Enter array size (q to quit) [200]:  Memory required:  158K.


LINPACK benchmark, Single precision.
Machine precision:  6 digits.
Array size 200 X 200.
Average rolled and unrolled performance:

    Reps Time(s) DGEFA   DGESL  OVERHEAD    KFLOPS
----------------------------------------------------
      32   0.96  92.36%   2.78%   4.85%  47915.387
      64   1.93  92.36%   2.78%   4.86%  47861.773
     128   3.87  92.36%   2.79%   4.85%  47737.379
     256   7.72  92.36%   2.78%   4.86%  47873.672
     512  15.45  92.35%   2.79%   4.86%  47831.438

```

**Comment by cbrake** [comment]
thanks @kraj  -- very interesting. Seems like decent amount of overhead for 64-bit with small reps. I also started looking at the generated code with the compiler explorer. Would also like to run a Go benchmark yet as well.

**Comment by kraj** [comment]
@cbrake Interesting to see go benchmark yes although I am not expecting a lot of difference between go and C benchmarks since runtime pretty much boils down to same instructions in the end.

**Comment by cbrake** [comment]
maybe try something like this: 

https://stackoverflow.com/questions/35162611/measure-flops-in-go

**Comment by cbrake** [comment]
One thing we do is represent all numbers as floats in a point, so I wonder if it makes sense to keep with float64 as then we can represent much larger ints? 

https://stackoverflow.com/questions/872544/what-range-of-numbers-can-be-represented-in-a-16-32-and-64-bit-ieee-754-syste

Looks like largest number for single precision is 2^23, for double, 2^52, which is probably large enough for any practical need.

I just thought of an issue -- we're currently encoding point values as floats in our protobuf encoding, so there is a mismatch between the go types and protobuf encoding -- we should probably fix that ASAP.

Overall, it seems we should be looking forward to 64-bit and optimizing for that  ...

**Comment by cbrake** [comment]
Javascript numbers are also doubles (64-bit), so more momentum in that direction.
