### ISSUE TITLE
Nats server start returned, this should not happen, exitting app! (improve startup/shutdown lifecycle)

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#307]
this seems to happen with I run with `siot_run`, but not with `./siot` -- not sure why yet.

**Comment by bminer** [comment]
I should also mention that in a Go app, once the main goroutine dies, the program will start to exit and does not wait on other goroutines. This could be why this error doesn't get displayed.

**Comment by cbrake** [comment]
should we be using context in more places to signal when we need to close? I'm sure there are places in the code that never exit, so we need to use context or channels to signal these areas we are shutting down.

**Comment by cbrake** [comment]
@bminer 

It does not seem like context is the right tool for global app  cancelation:

https://dave.cheney.net/2017/08/20/context-isnt-for-cancellation

> The documentation for the context package strongly recommends that context.Context is only for request scoped values:
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx:
> ...
> However, context.Context‘s most important facility, broadcasting a cancellation signal, is incomplete as there is no way to wait for the signal to be acknowledged.
> 

So seems like we need to roll our own or find another package.

I'm being forced address this in my work on #385. I need a way to spin up the SIOT server quickly in unit tests for e2e testing, so need to figure this out. Been looking through NATs code for ideas.

**Comment by cbrake** [comment]
@bminer this looks like a nice solution:

https://pkg.go.dev/github.com/oklog/run

Some context:

* https://blog.gopheracademy.com/advent-2017/run-group/
* https://www.youtube.com/watch?t=15m45s&v=LHe1Cb_Ud_M

The nice thing about oklog/run is that if any actor stops, it starts an orderly shutdown of the rest of the app, and logs the error from the one that initiated the shutdown. Brilliant!

Integrating now in #386

**Comment by bminer** [comment]
Sorry for chiming in a little late here. Yeah, `context` is probably not a good way to handle app shutdown. It's more of a clean up mechanism to abort requests or discrete actions.

Anyway, in this case, I think just removing the `log.Fatal` statement would help solve this problem. It's not entirely clear to me why multiple actors need to shutdown in tandem.

**Comment by cbrake** [comment]
implemented in #389
