### ISSUE TITLE
merge nats package into top level simpleiot?

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#348]
Since the nats package is what most Go users will interact with, should we move this functionality to the top level to keep things simpler? This would also be the API that packages for other languages would typically implement.

@bminer

**Comment by bminer** [comment]
It is not clear to me where the functionality should be separated, but some separation is needed for sure. There should be a "library" version of SIOT with some sort of API exposed (probably one that writes to NATS and the database) and then the "full app" version of SIOT with the Elm UI, etc etc.

**Comment by cbrake** [comment]
I'm thinking the https://pkg.go.dev/github.com/simpleiot/simpleiot package should expose the "library" functionality, and everything else will just build on that. So the idea is that someone who just wants to write a SIOT client, and just use github.com/simpleiot/simpleiot. Perhaps the simpleiot/data package could even be rolled into this as well. However, we'd likely quickly run into circular dependency issues.

**Comment by bminer** [comment]
Yeah, I think that `simpleiot/data` should be a part of the "core" / "library" package.

Then, I suppose you'd have `simpleiot/cli` and `simpleiot/web` and other similar things built on top of the core lib.

**Comment by cbrake** [comment]
what do you think of continuing to use `cmd/<app>/main.go` convention for everything that compiles to an exe (vs cli)? This seems to be fairly common practice in Go repos.

**Comment by cbrake** [comment]
nats package has been merged with client package. As I continue to simplify things, the architecture of SIOT is simplifying down to:

* server: NATS server, store, auth, etc
* clients: everything else -- rules, IO drivers, upstream connection, influxdb, etc.

Clients can be bundled inside the SIOT app, or can run as separate processes (local or remote).

**Comment by bminer** [comment]
@cbrake - Yeah, `cmd/<app>/main.go` seems like a good convention to follow, especially if there will be more than one executable.
