### ISSUE TITLE
create command line options to send custom samples

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#35]
This will allow any computer to function as a simple iot device by doing something like:

`siot -id=ab23124 -value=23.5 -index=1 -portal=https://portal.mysiotinstance.com -apikey=28341291sasdf2234 type=temp`

Will allow the following:

- makes it easy to test/evaluate SIOT
- enable sending data to a SIOT from scripts (backups, cron jobs, etc)

**Comment by kdsch** [comment]
A few questions:

- Why use command-line flags for data when the user could pipe in JSON? `siot ... <test.json` If data types change, CLI flags have to be updated. Whereas we can check correctness of arbitrary JSON payloads against internal data structures.
- What's the advantage of this over a shell script using curl?

**Comment by cbrake** [comment]
the advantage I see is ease of use -- it is a pain to manually format JSON and using curl is also a little tedious -- I would really like to have an easy way to evaluate/send data to the system.

The command line option I have in mind is:

```
-send string
      Send sample to 'portal': 'devId:sensId:value:type'
```

piping JSON into the app is a clever idea -- that could be very useful in a production scenario, but I think it is a little cumbersome for "try it out" scenario.

I'm not overly concerned about types changing -- the Sample type using ID/value/type is fairly versatile and I would like to stick to a simple type like this as long as possible. However, if things change, then we could change/remove the command line options at that point.
