### ISSUE TITLE
No log window for linux x86

### ISSUE THREAD

**Issue by SuperChrim** [simpleiot/simpleiot#375]
I don't know if this is an Ubuntu problem or a siot problem. But all versions of siot that I have worked with, win64, linux-arm6, and linux-x86, all versions give me a log window with the exception of linux-x86.

**Comment by cbrake** [comment]
Thanks for the report -- I don't have an Ubuntu machine handy, so thus have not tested yet on it.

How are you starting siot? Are you doing this from a terminal, or clicking in a file explorer?

**Comment by SuperChrim** [comment]
I've been clicking in a file explorer.

**Comment by cbrake** [comment]
In Unbuntu, can you try opening a terminal first and then starting SIOT from the terminal?
