### ISSUE TITLE
Consider using Makefiles to encode build dependencies

### ISSUE THREAD

**Issue by kdsch** [simpleiot/simpleiot#46]
We currently use shell functions to encode build dependencies. While this is straightforward, it has two drawbacks:

- redundant dependencies can be satisfied multiple times, repeating terminal output and increasing build time
- only a shell can run shell functions, whereas executable files can be used by many other tools, such as entr.

Makefiles often poorly fit the task at hand, such as minimizing C/C++ builds. Make's more advanced features can quickly lead to unreadable code.

In our case, Make's dependency analyzer seems apt for such tasks as "run tests, then run the executable". We have little need of functionality beyond phony targets and basic recipes, like variables, functions, file inclusion, conditionals, pattern matching, or even regular file targets. Thus, we can avoid nearly all of the pitfalls of Makefiles and arrive at a clean description of our build dependencies. It might look like this:

```
all: test deps siot

deploy: deps
	gcloud app deploy cmd/portal

docs:
	. ./envsetup.sh; siot_build_docs

run: deps
	go run cmd/siot/main.go -sim

siot:
	go build -o siot cmd/siot/main.go

deps: frontend assets

frontend:
	. ./envsetup.sh; siot_build_frontend

assets:
	. ./envsetup.sh; siot_build_assets

test: 
	golint -set_exit_status ./...
	go vet ./...
	go test ./...

.PHONY: all deps frontend assets test
```

There may be other tools that provide dependency analysis without Make's baggage.

**Comment by cbrake** [comment]
closing this for now -- feel free to open PR if you find something that works well.

One thing I've been doing more is defining new commands in envsetup.sh:

```
genesis() {
  GOARCH= go run github.com/benbjohnson/genesis/cmd/genesis "$@"
}
```

Perhaps this can be better implemented with a make dependency. However, with everything building so fast (go/elm), at this point, optimizing build is not a priority compared to other things, so postponing this topic for now.
