### ISSUE TITLE
Expose API for store dump / import

### ISSUE THREAD

**Issue by bminer** [simpleiot/simpleiot#475]
Previously, SIOT CLI had dbDump and dbImport CLI flags that dumped / imported using a JSON file. It would be nice if this could be re-written and exposed via the store / server API where appropriate.

**Comment by cbrake** [comment]
I am thinking of switching to TOML import/export so it would be more human-usable (see #497). 

The data would be displayed as a tree instead of arrays of nodes, edges, etc to reflect how the user interacts with the data instead of the database.

Thoughts @bminer?

**Comment by bminer** [comment]
How would you use TOML to render the node tree?

**Comment by cbrake** [comment]
@bminer this is what i had in mind. A little more human readable than JSON. For machine interface, we already have NATS, and could directly access the SQLite db. Does this make sense?

```
- id: 1234-12340156asd
  type: device
  description: root device
  - id: 12341-23asdf1234
    type: group
    description: group2
  - id: 12912-123412341
    type: group
    description: group3
    - id: 123411-1219919293
      type: user
      firstName: Cliff
      email: xyas@asdfas.com
```

**Comment by bminer** [comment]
I like it! Even though we have the SQLite database, and there are great tools to access it, I still like the idea of having an import / export function. Not strictly needed, but nice to have.

**Comment by cbrake** [comment]
what is pushing me toward toml is to be able to easily specify the intial config when deploying new sites -- say in an ansible script.

**Comment by cbrake** [comment]
this is implemented:

https://pkg.go.dev/github.com/simpleiot/simpleiot@v0.14.4/client#ExportNodes

https://pkg.go.dev/github.com/simpleiot/simpleiot@v0.14.4/client#ImportNodes

**Comment by bminer** [comment]
I think `ExportNodes` should support `"root"` for the node ID.

**Comment by cbrake** [comment]
The default is to export all nodes:

https://docs.simpleiot.org/docs/user/configuration.html#configuration-export

Does this work for you?

**Comment by bminer** [comment]
I am talking about the API call. For example, in [the CLI code](https://github.com/simpleiot/simpleiot/blob/master/cmd/siot/main.go#L533-L539) you have to fetch the root node if the node ID is omitted. I'm saying this logic should be moved to the [`ExportNodes` API call](https://pkg.go.dev/github.com/simpleiot/simpleiot@v0.14.9/client#ExportNodes).
