### ISSUE TITLE
Switch to a different default web server port

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#495]
8080 is commonly used, so perhaps use something like 8118 as it is less likely to conflict with other services -- one less thing to worry about when deploying.

- [ ] update siot
- [ ] update caddy role

**Comment by gedw99** [comment]
https://pkg.go.dev/github.com/hashicorp/consul/sdk/freeport

**Comment by cbrake** [comment]
@gedw99 thanks for the freeport tip -- that looks useful. In this case, I'm trying to minimize conflicts for people who are deploying simple setups -- one instance on one server with very little infrastructure, or need of it. This is the base use-case for SIOT.
