### ISSUE TITLE
Declarative config

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#497]
support a YAML or TOML-based declarative config. This could be applied to an existing SIOT system to quickly configure it or make changes without using the UI.

**Comment by gedw99** [comment]
+1 will make it way easier for people to run examples .

Would be cool if there was an examples folder that used these configs so it’s easy to bootstrap the system

**Comment by gedw99** [comment]
Would it make sense for the config to be proto based ?

This will make the system more robust because changes in how the config is on disk will cope with different versions of the software better.

**Comment by gedw99** [comment]
Can I ask what the reason for yaml is ?

**Comment by cbrake** [comment]
my initial purpose for this is to have something easily human-readable. For machine configuration, we can use the existing NATS/node/points API to read or write the config.

**Comment by cbrake** [comment]
Did an investigation of TOML and YAML, and it seems YAML is much better at handling nested data. TOML is better for flatter, simpler config files.

**Comment by cbrake** [comment]
export progress:

![image](https://github.com/simpleiot/simpleiot/assets/402813/88276c12-b2c3-4675-9013-f79a4e505f9c)

The Go YAML tools are pretty nice -- you simply have to declare the struct tags, and the tools do the rest.

**Comment by cbrake** [comment]
I did strip out a lot of the extraneous info like key = "0", tombstone "0" edge points, etc.

**Comment by cbrake** [comment]
Go functions implemented in #634. Need to implement the UI yet ...
