### ISSUE TITLE
CAN BUS CRASH

### ISSUE THREAD

**Issue by WaynePetersIot10** [simpleiot/simpleiot#498]
I you try to add CAN node from 8080 web page system crashes without any socketcan available

023/01/27 12:49:58 CanBusClient: socketCan interface not found: route ip+net: invalid network interface name
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe18579]

goroutine 121 [running]:
github.com/simpleiot/simpleiot/client.(*CanBusClient).Run.func2()
	/home/w/simpleiot/client/can.go:141 +0x139
github.com/simpleiot/simpleiot/client.(*CanBusClient).Run(0xc0002823c0)
	/home/w/simpleiot/client/can.go:177 +0x1ec
github.com/simpleiot/simpleiot/client.(*clientState[...]).start.func1()
	/home/w/simpleiot/client/client-state.go:71 +0x71
created by github.com/simpleiot/simpleiot/client.(*clientState[...]).start
	/home/w/simpleiot/client/client-state.go:69 +0x6fa

**Comment by cbrake** [comment]
@WaynePetersIot10 thanks for reporting -- we'll take a look!

cc @collinbrake

**Comment by cbrake** [comment]
fixed in #601
