### ISSUE TITLE
AWS versus fly.io in docs

### ISSUE THREAD

**Issue by gedw99** [simpleiot/simpleiot#510]
The docs look awesome 

on https://simpleiot.net/docs/install/account its asking users to use AWS

Fly.io could be another possibility. It’s a lot easier for a user to get setup.

**Comment by gedw99** [comment]
Also fly has https://github.com/superfly/litefs

don’t know if you want this feature in siot but basically it allows the db to be HA as well as serverless in that it can be rehydrated.

**Comment by gedw99** [comment]
Sorry but I got tricked by their project being the same name !! 

https://github.com/awslabs/simpleiot-cli

**Comment by cbrake** [comment]
:-) Imitation is the sincerest form of flattery ...
