### ISSUE TITLE
change settings from verbs to adjectives

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#642]
disable -> disabled
control -> controlled

This is more consistent with industry.

Verbs should only be used for checkboxes that reset themselves.

**Comment by cbrake** [comment]
implemented in #684

**Comment by bminer** [comment]
I like this even though it may break a few things! Nice!

**Comment by cbrake** [comment]
Yes, figured it was easier to do now than later. I learned this by looking at HTML attributes ...
