### ISSUE TITLE
Mechanism to send file to device

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#65]
This initially will be used for sending update files to edge devices. In the past, we've had trouble with downloads of 3MB files stalling when using the Go http client. Proposing to do something like this:

* chunk file into say 50KB chunks and send as NATs message
* create API where you can give it an io.Reader, and device ID
* system verifies the device is connected, and then sends file to device/:id/pushfile
* the device subscribes to device/:id/file and processes any files coming in
* when file has been downloaded, and assembled, it sends a message to the local NATs server running on the device -- perhaps /device/:id/newfile
* the device would have an update handler that listens for newfile, and if the file coming in is an update file, process it.

This would give us a generic mechanism for pushing files to a device, and then handlers could be attached at either end to send or process the files.

**Comment by ColinSullivan1** [comment]
You could also publish to Jetstream which would hold streams of configuration chunks that can be pulled by the clients.

**Comment by cbrake** [comment]
Jetstream looks interesting, but feel I need to get grounded with NATS basics for now, and then look at more advanced options. Starting with a simple file chunker in NATS -- this allows us to deploy only the simple NATS client on the edge devices. First pass is implemented and working:

https://github.com/simpleiot/simpleiot/commit/66ad8908ddd80b0483d19b6ed6def90e884dcc6e

Also added edge and send-file apps to be able to easily test.

Need to implement chunk re-tries, more error handling etc yet.

One of the important things we need is to be able to re-try individual chunks of a file on slow Cat-M cellular networks -- this should drastically improve the reliability of sending files. We're currently seeing stalled http gets of large (3-5MB) files which require restarting the download, and we have one site which we've never been able to successfully update remotely, even after trying dozens of times. It can maintain a connection for normal sensor data just fine. Data over cellular networks is a challenge -- they are not reliable. It will be interesting to see how NATS connections work over these links -- especially sites with low signal.

**Comment by cbrake** [comment]
implemented in: https://github.com/simpleiot/simpleiot/blob/master/nats/file.go
