### ISSUE TITLE
choose license

### ISSUE THREAD

**Issue by cbrake** [simpleiot/simpleiot#7]
Candidates:

* https://www.apache.org/licenses/LICENSE-2.0.html
* https://spdx.org/licenses/0BSD.html

Caddy uses apache-2

**Comment by cbrake** [comment]
@kdsch leaning toward apache-2 -- do you have an opinion on this?

**Comment by kdsch** [comment]
I like the simplicity of the BSD license. But I don't have a strong opinion.

I find it more critical to discuss sustainability, which would probably influence the license decision. The SFOSC discussion of [business models](https://sfosc.org/docs/business-models/) is somewhere to start.

What do you think?

**Comment by cbrake** [comment]
here is another SFOSC discussion on business models: 
https://sfosc.org/docs/book/business-models/

we are currently in the "support" model. Where we want to end up is not clear to me right now. 

I like the patent and liability parts of the apache-2 license. It seems if companies want to use and participate in the sw, a patent clause is necessary. Also, it lends a bit of comfort to those using the sw.

MIT seems to be the most popular license.

Some more information:

https://en.wikipedia.org/wiki/Category:Software_using_the_Apache_license
https://en.wikipedia.org/wiki/Category:Software_using_the_MIT_license

I'm also in the process of reading "Intellectual Property and Open Source", but not finished with it yet. (it is a good book)

**Comment by cbrake** [comment]
committed to feature-ui2 branch
