### ISSUE TITLE
Influx client adds "text" and "value" for points when only one is needed

### ISSUE THREAD

**Issue by bminer** [simpleiot/simpleiot#722]
Problem code is here:

https://github.com/simpleiot/simpleiot/blob/1aeca67d5e5947f3aeaeb8d182f1c2fd2952665b/client/db.go#L242-L249

Should we instead only include "text" if the `point.Text` is **not** `""`. Similarly, do we need the "value" if the `point.Text` is set?

**Comment by cbrake** [comment]
in some cases, points may have both 0 and text "" is a valid point, so I'm not sure we make a reliable rule and would be inclined keep including both for now. 

Influxdb is also currently our audit log of config changes, and some of these changes to text "" might be valid change.

Long term, with the point changes discussed in https://github.com/simpleiot/simpleiot/blob/feature-adr-7/docs/adr/7-jetstream-store.md#messagesubject-encoding, we will then know the data type of each point, so I think then might be the right time to optimize how we store data in influx. Thoughts?

**Comment by bminer** [comment]
I completely agree. Closing for now.
